### ISSUE TITLE
vim hangs on filenames starting with /

### ISSUE THREAD

**Issue by cottrell** [d0c-s4vage/vim-morph#13]
OSX vim 7.4

debug log

fchdir() to previous dir
sourcing "/usr/share/vim/vim74/plugin/spellfile.vim"
finished sourcing /usr/share/vim/vim74/plugin/spellfile.vim
chdir(/usr/share/vim/vim74/plugin)
fchdir() to previous dir

Probably something trivial. Hoping someone knows what this is already.

**Comment by d0c-s4vage** [comment]
I know this is really old, but is this a vim-morph issue? I am able to load files starting with `/` just fine, with and without vim-morph installed.

**Comment by cottrell** [comment]
I have mostly forgotten about it so best to close. I stopped using morph after I lost some data so haven't been trying it recently.
