### ISSUE TITLE
bad patterns in readme deserve warning

### ISSUE THREAD

**Issue by cottrell** [d0c-s4vage/vim-morph#14]
The patterns on the README for enc/decrypt should be avoided. Complete data loss seems to happen when saving files and typing mismatching passwords. File gets saved with error message only.

**Comment by d0c-s4vage** [comment]
This could be made more robust, I'll see what I can do

**Comment by d0c-s4vage** [comment]
![vim_morph_failed_command](https://user-images.githubusercontent.com/5090146/55602359-023f9b80-571a-11e9-8592-ee60ebb8284e.gif)

For now this is better, I'll revisit it later and add more robust error checking, probably using vim's job* commands

**Comment by d0c-s4vage** [comment]
Also added a warning on the README
