### ISSUE TITLE
Cannot override `g:Morph_UserMorphs`

### ISSUE THREAD

**Issue by hauleth** [d0c-s4vage/vim-morph#2]
I am using NeoVim which uses `$XDG_CONFIG_DIR/nvim` to store configuration instead of `~/.vim`. This causes errors in my config and makes plugin unusable for me.

**Comment by d0c-s4vage** [comment]
Hrmm. Why doesn't overriding it work? I thought that should work... I'll
look into it more  tonight. Thanks for reporting this

**Comment by d0c-s4vage** [comment]
Fixed
